name: Build PortAudio lib
on:
  push:
permissions:
  contents: write
jobs:
  windows:
    runs-on: windows-2022
    strategy:
      matrix:
        platform: [x64, Win32]
        asio: ["-asio"]
        include:
          - platform: x64
            platform-suffix: 64bit
          - platform: Win32
            platform-suffix: 32bit
    env:
      LDFLAGS: "/Brepro"
    steps:
      - name: checkout portaudio
        uses: actions/checkout@v4
        with:
          repository: PortAudio/portaudio
          ref: v19.7.0
          path: portaudio
      - name: download and extract ASIO SDK
        if: matrix.asio
        run: |
          curl -L -o asiosdk.zip https://www.steinberg.net/asiosdk
          7z x asiosdk.zip
      - name: cmake configure
        run: |
          cmake -S portaudio -B build -A ${{ matrix.platform }} -D PA_USE_ASIO=${{ matrix.asio && 'ON' || 'OFF' }}
      - name: cmake build
        run: |
          cmake --build build --config Release
          ls -R
