name: Build PortAudio lib
on:
  push:
permissions:
  contents: write
jobs:
  windows:
    runs-on: windows-2022
    strategy:
      matrix:
        platform: [x64, Win32]
        asio: ["-asio"]
        include:
          - platform: x64
            platform-suffix: 64bit
          - platform: Win32
            platform-suffix: 32bit
    env:
      LDFLAGS: "/Brepro"
    steps:
      - name: cmake configure
        run: git clone https://github.com/PortAudio/portaudio --branch v19.7.0
          curl -L -o asiosdk.zip https://www.steinberg.net/asiosdk
          7z x asiosdk.zip
          cmake -S portaudio -B build -A ${{ matrix.platform }} -D PA_USE_ASIO=ON
          cmake --build build --config Release
          ls -R
