name: Build ASDF lib and run tests
on: [push]
jobs:
  linux:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    steps:
      - name: checkout portaudio
        uses: actions/checkout@v3
        with:
          repository: PortAudio/portaudio
          ref: v19.7.0
          path: portaudio
      - name: cmake configure
        run: |
          cmake -S portaudio -B build
      - name: cmake build
        run: |
          cmake --build build
      - name: upload build
        uses: actions/upload-artifact@v3
        with:
          name: manylinux-build
          path: build/*
